version: "3.3"

services:


  laravelDB:
    container_name: laravelDB
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ../_laravelDB_mysql57:/var/lib/mysql
      - ../_laravelDB_mysql57_log:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      # - MYSQL_ROOT_HOST=%
    command: --max_allowed_packet=128M  --innodb_buffer_pool_size=512M --wait_timeout=3600 --interactive_timeout=3600 --connect_timeout=600 --net_read_timeout=600 --net_write_timeout=600 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      das:
        ipv4_address: 172.18.0.3

  laravel:
    container_name: laravel
    # image: seokjoon/all:di.2    ## stage
    # image: seokjoon/all:di.1  ## local
    image: seokjoon/all:di.1.3  ## local
    restart: unless-stopped
    depends_on:
      - laravelDB
    ports:
      - 80:80
      - 443:443
    ## TODO: cd ../.. && ln -s ilark/daab_server ./
    volumes:
      # - ../:/var/www            ## stage
      # - ../../:/var/www       ## local
      - ../:/var/www       ## local
      - ../_daab_server_log:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      # - ../etc/letsencrypt:/etc/letsencrypt ## stage
    networks:
      das:
        ipv4_address: 172.18.0.4



networks:
  das:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
